In [2]:
import pandas as pd

# A DataFrame is pandas' core object: a table, like a spreadsheet in code
data = {
    "city": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Gqeberha"],
    "population_m": [5.8, 4.7, 3.9, 2.6, 1.3],
    "avg_temp_c": [16, 17, 21, 18, 18],
    "coastal": [False, True, True, False, True]
}
df = pd.DataFrame(data)
df

           city  population_m  avg_temp_c  coastal
0  Johannesburg           5.8          16    False
1     Cape Town           4.7          17     True
2        Durban           3.9          21     True
3      Pretoria           2.6          18    False
4      Gqeberha           1.3          18     True

In [3]:
df["population_m"].sum()

np.float64(18.3)

In [4]:
df[df["coastal"] == True]

        city  population_m  avg_temp_c  coastal
1  Cape Town           4.7          17     True
2     Durban           3.9          21     True
4   Gqeberha           1.3          18     True

In [5]:
df.sort_values("avg_temp_c")

           city  population_m  avg_temp_c  coastal
0  Johannesburg           5.8          16    False
1     Cape Town           4.7          17     True
3      Pretoria           2.6          18    False
4      Gqeberha           1.3          18     True
2        Durban           3.9          21     True

In [6]:
df["population_m"].mean()

np.float64(3.66)